from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.units import inch

def create_tenses_pdf(filename):
    doc = SimpleDocTemplate(filename, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, spaceAfter=20, alignment=1, textColor=colors.darkblue)
    header_style = ParagraphStyle('Header', parent=styles['Heading2'], fontSize=16, spaceBefore=15, spaceAfter=10, textColor=colors.darkred)
    sub_header_style = ParagraphStyle('SubHeader', parent=styles['Heading3'], fontSize=14, spaceBefore=10, spaceAfter=5, textColor=colors.black)
    normal_style = styles['Normal']
    code_style = ParagraphStyle('Code', parent=styles['Code'], fontSize=10, backColor=colors.lightgrey, borderPadding=5)

    story = []

    # --- Title Page ---
    story.append(Paragraph("The Complete Guide to English Tenses", title_style))
    story.append(Paragraph("Definitions, Formulas, Examples, and Practice Exercises", styles['Heading2']))
    story.append(Spacer(1, 2*inch))
    story.append(Paragraph("<b>Generated by your AI Assistant</b>", styles['Normal']))
    story.append(PageBreak())

    # --- Content Data ---
    tenses_data = [
        {
            "type": "Present Tense",
            "subtypes": [
                {
                    "name": "Simple Present",
                    "def": "Used for facts, generalizations, and habitual actions.",
                    "formula": "Subject + V1 (s/es) + Object",
                    "example": "She writes a letter. / The sun rises in the east."
                },
                {
                    "name": "Present Continuous",
                    "def": "Used for actions happening right now or temporary situations.",
                    "formula": "Subject + is/am/are + V1(-ing) + Object",
                    "example": "She is writing a letter right now."
                },
                {
                    "name": "Present Perfect",
                    "def": "Used for actions completed recently or experience where time is not specified.",
                    "formula": "Subject + has/have + V3 + Object",
                    "example": "She has written a letter."
                },
                {
                    "name": "Present Perfect Continuous",
                    "def": "Used for actions that started in the past and are still continuing.",
                    "formula": "Subject + has/have + been + V1(-ing) + Object",
                    "example": "She has been writing a letter for two hours."
                }
            ]
        },
        {
            "type": "Past Tense",
            "subtypes": [
                {
                    "name": "Simple Past",
                    "def": "Used for actions completed at a specific time in the past.",
                    "formula": "Subject + V2 + Object",
                    "example": "She wrote a letter yesterday."
                },
                {
                    "name": "Past Continuous",
                    "def": "Used for actions that were ongoing at a specific moment in the past.",
                    "formula": "Subject + was/were + V1(-ing) + Object",
                    "example": "She was writing a letter when I called."
                },
                {
                    "name": "Past Perfect",
                    "def": "Used for an action that was completed before another action in the past.",
                    "formula": "Subject + had + V3 + Object",
                    "example": "She had written the letter before he arrived."
                },
                {
                    "name": "Past Perfect Continuous",
                    "def": "Used to show that an action started in the past and continued up to another point in the past.",
                    "formula": "Subject + had + been + V1(-ing) + Object",
                    "example": "She had been writing for an hour when the power went out."
                }
            ]
        },
        {
            "type": "Future Tense",
            "subtypes": [
                {
                    "name": "Simple Future",
                    "def": "Used for actions that will happen in the future.",
                    "formula": "Subject + will/shall + V1 + Object",
                    "example": "She will write a letter tomorrow."
                },
                {
                    "name": "Future Continuous",
                    "def": "Used for actions that will be in progress at a specific time in the future.",
                    "formula": "Subject + will + be + V1(-ing) + Object",
                    "example": "She will be writing a letter at 5 PM."
                },
                {
                    "name": "Future Perfect",
                    "def": "Used for actions that will be completed by a certain time in the future.",
                    "formula": "Subject + will + have + V3 + Object",
                    "example": "She will have written the letter by evening."
                },
                {
                    "name": "Future Perfect Continuous",
                    "def": "Used to emphasize the duration of an action up to a certain point in the future.",
                    "formula": "Subject + will + have + been + V1(-ing) + Object",
                    "example": "She will have been writing for three hours by the time you arrive."
                }
            ]
        }
    ]

    # --- Generative Content Loop ---
    for tense_cat in tenses_data:
        story.append(Paragraph(tense_cat['type'], header_style))
        story.append(Spacer(1, 0.1*inch))
        
        for subtype in tense_cat['subtypes']:
            # Create a table for each tense for better layout
            data = [
                [Paragraph(f"<b>{subtype['name']}</b>", sub_header_style), ''],
                ["Definition:", Paragraph(subtype['def'], normal_style)],
                ["Formula:", Paragraph(subtype['formula'], code_style)],
                ["Example:", Paragraph(subtype['example'], normal_style)]
            ]
            
            t = Table(data, colWidths=[1.5*inch, 4.5*inch])
            t.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.lightgrey),
                ('PADDING', (0,0), (-1,-1), 6),
            ]))
            story.append(t)
            story.append(Spacer(1, 0.2*inch))
        
        story.append(PageBreak())

    # --- Practice Exercises ---
    story.append(Paragraph("Practice Exercises", header_style))
    story.append(Paragraph("Identify the tense or fill in the correct form of the verb:", normal_style))
    story.append(Spacer(1, 0.2*inch))

    exercises = [
        "1. I __________ (go) to the gym every morning. (Simple Present)",
        "2. Look! The bird __________ (fly) away. (Present Continuous)",
        "3. She __________ (finish) her homework already. (Present Perfect)",
        "4. They __________ (live) in this city for ten years. (Present Perfect Continuous)",
        "5. We __________ (watch) a movie yesterday. (Simple Past)",
        "6. I __________ (sleep) when the phone rang. (Past Continuous)",
        "7. The train __________ (leave) before we reached the station. (Past Perfect)",
        "8. He __________ (work) there for 5 years before he quit. (Past Perfect Continuous)",
        "9. I __________ (call) you tomorrow. (Simple Future)",
        "10. At 8 PM tonight, I __________ (eat) dinner. (Future Continuous)",
        "11. By next year, we __________ (complete) the project. (Future Perfect)",
        "12. By 2030, she __________ (teach) for 20 years. (Future Perfect Continuous)"
    ]

    for ex in exercises:
        story.append(Paragraph(ex, normal_style))
        story.append(Spacer(1, 0.1*inch))

    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("<b>Answer Key:</b>", sub_header_style))
    
    answers = [
        "1. go", "2. is flying", "3. has finished", "4. have been living",
        "5. watched", "6. was sleeping", "7. had left", "8. had been working",
        "9. will call", "10. will be eating", "11. will have completed", "12. will have been teaching"
    ]
    
    for ans in answers:
        story.append(Paragraph(ans, normal_style))

    # Build PDF
    doc.build(story)
    print(f"PDF generated successfully: {filename}")

if __name__ == "__main__":
    create_tenses_pdf("English_Tenses_Guide.pdf")